export const SEED_PROFILE = {
  name: 'Adhyayan Gupta',
  age: 20,
  heightCm: 188.0,
  currentWeightKg: 107.0,
  goalWeightKg: 94.0,
  goalBodyFatPercent: 20.0,
  dailyCaloriesKcal: 2500,
  dailyProteinG: 160,
  dailyWaterMl: 4000,
  dailySteps: 10000,
  sleepTargetHours: 8.0,
};

export const SEED_WORKOUT_SPLIT = ['Push', 'Pull', 'Legs', 'Rest', 'Upper', 'Lower', 'Arms + Core'];

export const SEED_CATEGORIES = ['Career', 'Fitness', 'College', 'Personal', 'Shopping'];

export const SEED_HABITS = [
  'Gym',
  '10k Steps',
  'Protein Goal',
  'Calories Goal',
  'Drink 4L Water',
  'Read 30 Minutes',
  'Sleep Before Midnight',
  'Journal',
  'Apply to 5 Companies',
  'Study GTM 2 Hours',
];

/** ~Top 10 movements per muscle group — the workout tracker's catalog. */
export const SEED_EXERCISES: Record<string, string[]> = {
  chest: [
    'Barbell Bench Press',
    'Incline Barbell Press',
    'Flat Dumbbell Press',
    'Incline Dumbbell Press',
    'Weighted Dip',
    'Cable Fly',
    'Pec Deck',
    'Machine Chest Press',
    'Low-to-High Cable Fly',
    'Push-Up',
  ],
  lats: [
    'Pull-Up',
    'Lat Pulldown',
    'Barbell Row',
    'Seated Cable Row',
    'Single-Arm Dumbbell Row',
    'T-Bar Row',
    'Chest-Supported Row',
    'Straight-Arm Pulldown',
    'Deadlift',
    'Rack Pull',
  ],
  biceps: [
    'Barbell Curl',
    'EZ-Bar Curl',
    'Dumbbell Curl',
    'Hammer Curl',
    'Incline Dumbbell Curl',
    'Preacher Curl',
    'Cable Curl',
    'Concentration Curl',
    'Spider Curl',
    'Reverse Curl',
  ],
  triceps: [
    'Close-Grip Bench Press',
    'Skull Crusher',
    'Cable Pushdown',
    'Rope Pushdown',
    'Overhead Cable Extension',
    'Overhead Dumbbell Extension',
    'Triceps Dip',
    'Machine Dip',
    'Dumbbell Kickback',
    'Diamond Push-Up',
  ],
  shoulders: [
    'Overhead Press',
    'Seated Dumbbell Press',
    'Arnold Press',
    'Machine Shoulder Press',
    'Lateral Raise',
    'Cable Lateral Raise',
    'Rear Delt Fly',
    'Face Pull',
    'Front Raise',
    'Upright Row',
  ],
  legs: [
    'Back Squat',
    'Front Squat',
    'Leg Press',
    'Romanian Deadlift',
    'Bulgarian Split Squat',
    'Walking Lunge',
    'Leg Extension',
    'Leg Curl',
    'Hip Thrust',
    'Standing Calf Raise',
  ],
  abs: [
    'Hanging Leg Raise',
    'Hanging Knee Raise',
    'Cable Crunch',
    'Machine Crunch',
    'Ab Wheel Rollout',
    'Decline Sit-Up',
    'Russian Twist',
    'Plank',
    'Side Plank',
    'Mountain Climber',
  ],
};

export const SEED_DASHBOARD_WIDGET_ORDER = [
  'todaysWeight',
  'todaysWorkout',
  'caloriesRemaining',
  'proteinProgress',
  'waterIntake',
  'habitCompletion',
  'tasksRemaining',
  'weeklyWeightGraph',
  'workoutStreak',
  'currentGoal',
] as const;
