/**
 * Static snapshot of timetable.md's 30 day blocks — generated once, not
 * read from the file at runtime (Next's serverless bundle doesn't reliably
 * ship arbitrary repo files). Regenerate by hand if the plan changes.
 */
export const TIMETABLE_TODOS: Array<{ title: string; dueDate: string; notes: string }> = [
  { title: "Day 1 — GTM map and vocabulary", dueDate: "2026-08-20", notes: "Understand the full revenue workflow and where engineering creates leverage.\n\nDeliverable: GTM architecture diagram + ICP document committed to GitHub.\n\nDone when: You can explain each handoff and name the system of record for it." },
  { title: "Day 2 — CRM fundamentals in HubSpot", dueDate: "2026-08-21", notes: "Operate a CRM manually before automating it.\n\nDeliverable: Populated test CRM + documented schema and pipeline.\n\nDone when: You can show how a contact relates to a company and deal, and why each property exists." },
  { title: "Day 3 — HubSpot API: CSV to CRM", dueDate: "2026-08-22", notes: "Write a safe, repeatable CRM importer.\n\nDeliverable: `csv_to_hubspot` script, sample CSV, setup instructions, and terminal-output screenshot.\n\nDone when: Running it twice does not create duplicate records (idempotency)." },
  { title: "Day 4 — HTTP and API reliability", dueDate: "2026-08-23", notes: "Understand how integrations fail and design for it.\n\nDeliverable: Reusable API client + reliability documentation.\n\nDone when: You can demonstrate a rate-limit or temporary-error simulation without losing or duplicating data." },
  { title: "Day 5 — Webhooks and event-driven workflows", dueDate: "2026-08-24", notes: "Receive, validate, and process an event safely.\n\nDeliverable: Webhook receiver with test payloads and `docs/webhook-design.md`.\n\nDone when: Duplicate deliveries cause no duplicate business action." },
  { title: "Day 6 — Start the main project: architecture and repository", dueDate: "2026-08-25", notes: "Turn isolated labs into one revenue-engineering system.\n\nDeliverable: Main-project README, diagram, backlog, `.env.example`, and initial scaffold.\n\nDone when: A reviewer can understand the business value and system flow in five minutes." },
  { title: "Day 7 — Week 1 review and public proof", dueDate: "2026-08-26", notes: "Consolidate and expose what you built.\n\nDeliverable: Week 1 retrospective, clean repositories, and one public update.\n\nDone when: All Week 1 projects have run instructions and no secrets in Git history." },
  { title: "Day 8 — n8n fundamentals", dueDate: "2026-08-27", notes: "Build an automation workflow without hiding the logic.\n\nDeliverable: Versioned n8n workflow with a working test run.\n\nDone when: You can replay a test event and trace every step in execution history." },
  { title: "Day 9 — Enrichment design", dueDate: "2026-08-28", notes: "Add useful data while respecting data quality and authorization.\n\nDeliverable: Enrichment module + before/after sample records + data dictionary.\n\nDone when: Every enriched field says where it came from and when it was last updated." },
  { title: "Day 10 — Lead scoring and qualification", dueDate: "2026-08-29", notes: "Convert an ICP into explicit, testable logic.\n\nDeliverable: Lead-score module, tests, and scoring policy.\n\nDone when: You can change a score rule without rewriting the workflow." },
  { title: "Day 11 — CRM routing and ownership", dueDate: "2026-08-30", notes: "Assign qualified records correctly and visibly.\n\nDeliverable: Routing module, configuration table, workflow export, and tests.\n\nDone when: Every lead has exactly one owner or an explicit review status." },
  { title: "Day 12 — SQL and operational data store", dueDate: "2026-08-31", notes: "Make the system auditable beyond the CRM.\n\nDeliverable: Schema/migration, seed data, and six saved SQL queries.\n\nDone when: You can answer “what happened to this lead?” from the data store." },
  { title: "Day 13 — Orchestrate the full workflow", dueDate: "2026-09-01", notes: "Connect input, transformation, CRM, logging, and notification.\n\nDeliverable: First end-to-end project demo and a reproducible sample run.\n\nDone when: A 50-lead run produces a summary and leaves the CRM/database in the expected state." },
  { title: "Day 14 — Week 2 QA and case study", dueDate: "2026-09-02", notes: "Make the workflow reliable enough to show.\n\nDeliverable: QA report and Week 2 project release/tag.\n\nDone when: Known failure cases are handled or explicitly surfaced, never silently ignored." },
  { title: "Day 15 — Outbound foundations and ethical copy", dueDate: "2026-09-03", notes: "Understand outbound as a controlled system, not message blasting.\n\nDeliverable: `docs/outbound-copy.md` and message-template module.\n\nDone when: Each email is specific, under 120 words, includes a clear CTA, and has no fabricated personalization." },
  { title: "Day 16 — Sequence state machine", dueDate: "2026-09-04", notes: "Model follow-up logic safely.\n\nDeliverable: State diagram + sequence engine simulation.\n\nDone when: No simulated lead can remain in an active sequence after a stop condition." },
  { title: "Day 17 — Email events and CRM updates", dueDate: "2026-09-05", notes: "Process engagement events accurately.\n\nDeliverable: Event processor + event mapping documentation.\n\nDone when: Replaying the same event or receiving it late produces the correct final state." },
  { title: "Day 18 — Funnel metrics and dashboard queries", dueDate: "2026-09-06", notes: "Measure the system rather than merely automate it.\n\nDeliverable: Dashboard screenshots plus documented formulas.\n\nDone when: A reader can identify the largest drop-off and propose a test from the dashboard." },
  { title: "Day 19 — Experiment design and attribution", dueDate: "2026-09-07", notes: "Learn to improve GTM systems scientifically.\n\nDeliverable: Experiment brief, attribution queries, and sample analysis.\n\nDone when: You can distinguish correlation, attribution, and causation in your project explanation." },
  { title: "Day 20 — Data quality and observability", dueDate: "2026-09-08", notes: "Detect system decay before revenue teams complain.\n\nDeliverable: Quality-check module/report and observability documentation.\n\nDone when: You can locate a failed record and identify why it failed in under five minutes." },
  { title: "Day 21 — Week 3 release and portfolio review", dueDate: "2026-09-09", notes: "Make an honest, compelling portfolio artifact.\n\nDeliverable: Video/demo link in README, case study, and feedback log.\n\nDone when: Someone unfamiliar with the project can describe its value and architecture back to you." },
  { title: "Day 22 — Authentication, privacy, and compliance", dueDate: "2026-09-10", notes: "Show you can build responsibly around customer data.\n\nDeliverable: Security/privacy checklist and sanitized repositories.\n\nDone when: You can explain how credentials and personal data are protected in the demo system." },
  { title: "Day 23 — Failure recovery and idempotency", dueDate: "2026-09-11", notes: "Make retries safe.\n\nDeliverable: Failure-recovery runbook + tested replay mechanism.\n\nDone when: You can rerun a failed job without creating duplicate CRM records or notifications." },
  { title: "Day 24 — Improve architecture and code quality", dueDate: "2026-09-12", notes: "Make the project readable and maintainable.\n\nDeliverable: Refactored codebase with a quality checklist.\n\nDone when: A new contributor can identify where to change scoring or routing in under two minutes." },
  { title: "Day 25 — Build a lightweight operator console/report", dueDate: "2026-09-13", notes: "Surface the information a GTM operator needs each day.\n\nDeliverable: Operator console/report integrated into the project README.\n\nDone when: An operator can decide what needs attention without reading raw logs." },
  { title: "Day 26 — Simulated production run", dueDate: "2026-09-14", notes: "Prove the full system under a realistic batch.\n\nDeliverable: Production-simulation report with before/after results.\n\nDone when: You have measured evidence that the system behaves correctly at batch scale." },
  { title: "Day 27 — Portfolio packaging", dueDate: "2026-09-15", notes: "Package your work for a recruiter, founder, or hiring manager.\n\nDeliverable: Recruiter-ready GitHub repository.\n\nDone when: The README answers “what, why, how, proof, and trade-offs” without requiring a call." },
  { title: "Day 28 — Job-market research and targeting", dueDate: "2026-09-16", notes: "Align your portfolio with real GTM Engineering work.\n\nDeliverable: Job-requirements matrix and tailored project bullet points.\n\nDone when: You can explain why this portfolio matches specific job requirements." },
  { title: "Day 29 — Interview readiness and outreach assets", dueDate: "2026-09-17", notes: "Become able to discuss the work credibly.\n\nDeliverable: `docs/interview-qa.md`, resume bullets, and feedback-request template.\n\nDone when: You can explain the entire project without opening code." },
  { title: "Day 30 — Final demo, audit, and next 60 days", dueDate: "2026-09-18", notes: "Finish with verifiable evidence and a continuation plan.\n\nDeliverable: Final tagged release, working demo, final post, and 60-day continuation plan.\n\nDone when: A stranger can clone/run the project or inspect the demo and verify your claims." },
];
